#!/usr/bin/env sh

set -e -u

# see: https://stackoverflow.com/a/20434740
DIR="$( cd "$( dirname "$0" )" && pwd )"
BINDIR=$HOME/.local/bin
CHEZMOI="$BINDIR/chezmoi"

# install chezmoi into BINDIR
export BINDIR
curl -fsSL "https://chezmoi.io/get" | sh

# apply dotfiles
chmod 700 "$DIR"
"$CHEZMOI" apply --source "$DIR"

