# Base16 Solarized Light (extended colors)
# Source: https://github.com/aarowill/base16-alacritty/blob/master/colors/base16-solarized-light-256.toml

# Colors the cursor will use if `custom_cursor_colors` is true
[colors.cursor]
text = '#fdf6e3'
cursor = '#586e75'

# Default colors
[colors.primary]
background = '#fdf6e3'
foreground = '#586e75'

# Normal colors
[colors.normal]
black = '#fdf6e3'
red = '#dc322f'
green = '#859900'
yellow = '#b58900'
blue = '#268bd2'
magenta = '#6c71c4'
cyan = '#2aa198'
white = '#586e75'

# Bright colors
[colors.bright]
black = '#839496'
red = '#dc322f'
green = '#859900'
yellow = '#b58900'
blue = '#268bd2'
magenta = '#6c71c4'
cyan = '#2aa198'
white = '#002b36'

[[colors.indexed_colors]]
index = 16
color = "#cb4b16"

[[colors.indexed_colors]]
index = 17
color = "#d33682"

[[colors.indexed_colors]]
index = 18
color = "#eee8d5"

[[colors.indexed_colors]]
index = 19
color = "#93a1a1"

[[colors.indexed_colors]]
index = 20
color = "#657b83"

[[colors.indexed_colors]]
index = 21
color = "#073642"
